# -*- coding: utf-8 -*-
"""CA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CUNrCXeBojDrZc1veBvBAn_bohq75FXc
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("datasnaek/youtube-new")

print("Path to dataset files:", path)

import os

# List the contents of the downloaded dataset directory
print(os.listdir(path))

import pandas as pd
import os

# Construct the full path to one of the CSV files
file_path = os.path.join(path, 'DEvideos.csv')

# Load the CSV file into a pandas DataFrame
df = pd.read_csv(file_path)

# Display the first 5 rows of the DataFrame
display(df.head())
len(df)

"""**MERGING ALL THE FILES TOGETHER**"""

import pandas as pd
import os
import glob

# 1. Get a list of all CSV files in that folder
all_files = glob.glob(os.path.join(path, "*.csv"))

df_list = []
for file in all_files:
    temp_df = pd.read_csv(file, encoding='latin-1')

    temp_df['region'] = os.path.basename(file)[:2]

    df_list.append(temp_df)

df = pd.concat(df_list, ignore_index=True)

print(f"Total rows loaded: {len(df)}")

"""**HANDLING MISSING VALUES**"""

df.isnull().sum().sum()

df.isnull().sum()

df['description']=df['description'].fillna('NO DESCRIPTION!!')

df.isnull().sum().sum()

"""**INTEGRITY CHECK**"""

import pandas as pd

# Convert 'publish_time' and 'trending_date' to datetime objects
df['publish_time'] = pd.to_datetime(df['publish_time'])
df['trending_date'] = pd.to_datetime(df['trending_date'], format='%y.%d.%m')

# A video cannot be trending before it was published
time_error = df[df['publish_time'].dt.date > df['trending_date'].dt.date]
print(f"{len(time_error)} videos trended before they were published")

# Check data types of all columns
print(df.dtypes)
#to find if any numeric value contained some non-numeric values
non_numeric_likes = pd.to_numeric(df['likes'], errors='coerce').isna().sum()
print(f"Non-numeric values in 'likes': {non_numeric_likes}")

# List unique values in the boolean columns
print("Values in comments_disabled:", df['comments_disabled'].unique())
print("Values in ratings_disabled:", df['ratings_disabled'].unique())

"""**REMOVING DUPLICATES**"""

# Remove rows where every single column is same
df = df.drop_duplicates()
print(f"Rows after removing exact duplicates: {len(df)}")

# Count how many times each video ID appears
duplicate_counts = df['video_id'].value_counts()
print(df['video_id'].duplicated().sum(), "duplicate entries found.")

# 1. Sort by views (highest to lowest)
df = df.sort_values('views', ascending=False)

# 2. Keep only the first (highest view) entry for each unique video
df_unique_videos = df.drop_duplicates(subset='video_id', keep='first')

print(f"Unique videos found: {len(df_unique_videos)}")

total_rows = len(df)

unique_count = df['video_id'].nunique()

extra_entries = df.duplicated(subset='video_id').sum()
print(f"Unique ({unique_count}) + Extra ({extra_entries}) = {unique_count + extra_entries}")
print(f"Actual Total Rows: {total_rows}")

"""**STANDARDIZATION**


*   Already standardized the "publish_time" and "trending_date" colmuns during integrity checking part.

"""

# Create standardized engagement ratios
df['likes_per_view'] = df['likes'] / df['views']
df['comments_per_view'] = df['comment_count'] / df['views']
print(df[['likes_per_view', 'comments_per_view']].head())

"""**OUTLIERS**"""

# Calculate IQR for the 'views' column
Q1 = df['views'].quantile(0.25)
Q3 = df['views'].quantile(0.75)
IQR = Q3 - Q1

# Defining the boundary
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Find the outliers
outliers = df[(df['views'] < lower_bound) | (df['views'] > upper_bound)]

print(f"Typical View Range: {lower_bound} to {upper_bound}")
print(f"Total Outliers detected: {len(outliers)}")

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 5))
sns.boxplot(x=df['views'])
plt.title('Detection of View Outliers')
plt.show()

# REMOVAL OF OUTLIERS
df_trimmed = df[df['views'] <= upper_bound].copy()

print(f"Original rows: {len(df)}")
print(f"Rows after trimming: {len(df_trimmed)}")
print(f"Max views in trimmed data: {df_trimmed['views'].max()}")

#SCALING
import numpy as np
df['views_log'] = np.log1p(df['views'])

# Visualize the difference
import seaborn as sns
import matplotlib.pyplot as plt

plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
sns.histplot(df['views'], bins=50).set_title("Original Views (Skewed)")

plt.subplot(1, 2, 2)
sns.histplot(df['views_log'], bins=50).set_title("Log Transformed Views (Normalized)")
plt.show()

#LABELLING
def label_outliers(view_count):
    if view_count > upper_bound:
        return 'Viral Outlier'
    else:
        return 'Standard Trending'

df['video_type'] = df['views'].apply(label_outliers)
print(df['video_type'].value_counts())
print(df.groupby('video_type')['likes'].mean())