# -*- coding: utf-8 -*-
"""CSA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1loRo1RVQiLNmFZ5838kR-Fc7MxDqnb46

# **ARYA TIWARI**
"""

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

data_source="https://raw.githubusercontent.com/Arya17-git/OIBSIP/refs/heads/main/Task-2-Customer-Segmentation/ifood_df.csv"
data=pd.read_csv(data_source)
data.head(5)

print(data.info())

data.describe()

data.isnull().sum().sum()

data.size

data.shape

categories = {
    "Demographics": [
        "Age", "Income", "Kidhome", "Teenhome", "Customer_Days",
        "marital_Divorced", "marital_Married", "marital_Single", "marital_Together", "marital_Widow",
        "education_2n Cycle", "education_Basic", "education_Graduation", "education_Master", "education_PhD"
    ],
    "Product Spending": [
        "MntWines", "MntFruits", "MntMeatProducts", "MntFishProducts",
        "MntSweetProducts", "MntGoldProds", "MntTotal", "MntRegularProds"
    ],
    "Channels & Behavior": [
        "NumDealsPurchases", "NumWebPurchases", "NumCatalogPurchases",
        "NumStorePurchases", "NumWebVisitsMonth", "Recency"
    ],
    "Marketing Campaigns": [
        "AcceptedCmp1", "AcceptedCmp2", "AcceptedCmp3", "AcceptedCmp4",
        "AcceptedCmp5", "AcceptedCmpOverall", "Response", "Complain"
    ]
}

# Print to confirm they are all found
for category, cols in categories.items():
    found = [c for c in cols if c in data.columns]
    print(f"{category}: {len(found)} columns identified.")

"""**DESCRIPTIVE** **STATISTICS**"""

demo_cols = ['Age', 'Income', 'Kidhome', 'Teenhome']
print(data[demo_cols].describe())

campaign_cols = ['AcceptedCmpOverall', 'Response','Complain']
print(data[campaign_cols].describe())

mnt_cols = ['MntWines', 'MntFruits', 'MntMeatProducts', 'MntFishProducts', 'MntSweetProducts', 'MntGoldProds']
print(data[mnt_cols].describe())

#KEY PERFORMANCE INDICATORS
data['Totalpurchases']=data['NumWebPurchases']+data['NumCatalogPurchases']+data['NumStorePurchases']+data['NumCatalogPurchases']

avg_purchase_value=data['MntTotal'].sum()/data['Totalpurchases'].sum()
print(f"Average Purchase Value: ${avg_purchase_value:.2f}")

avg_frequency=data['Totalpurchases'].mean()
print(f"Average Purchase Frequency: {avg_frequency:.2f}")

avg_income=data['Income'].mean()
print(f"Average Income: ${avg_income:.2f}")

avg_spending=data['MntTotal'].mean()
print(f"Average Spending: ${avg_spending:.2f}")

avg_recency=data['Recency'].mean()
print(f"Average Recency: {avg_recency:.2f}")

data[mnt_cols].mean().sort_values().plot(kind='barh', color='purple')
plt.title('Average Spend by Product Category')
plt.xlabel('Amount ($)')
plt.show()

"""**CUSTOMER SEGMENTATION**"""

#FEATURE SELECTION & SCALING
features = ['Income', 'MntTotal', 'Recency', 'NumWebPurchases', 'NumStorePurchases']
data_to_cluster = data[features]

scaler = StandardScaler()
scaled_features = scaler.fit_transform(data_to_cluster)

#ELBOW METHOD
wcss = [] # Within-Cluster Sum of Square
for i in range(1, 11):
    kmeans = KMeans(n_clusters=i, init='k-means++', random_state=42)
    kmeans.fit(scaled_features)
    wcss.append(kmeans.inertia_)

# Plotting the Elbow
plt.figure(figsize=(8, 5))
plt.plot(range(1, 11), wcss, marker='o', linestyle='--')
plt.title('Elbow Method to Determine Optimal Clusters')
plt.xlabel('Number of Clusters')
plt.ylabel('WCSS')
plt.show()

#K-MEANS CLUSTERING
kmeans = KMeans(n_clusters=4, init='k-means++', random_state=42)
clusters = kmeans.fit_predict(scaled_features)

data['Cluster'] = clusters

cluster_summary = data.groupby('Cluster')[features].mean()
print(cluster_summary)

# Calculate the mean of each key feature for every cluster
profile = data.groupby('Cluster')[['Income', 'MntTotal', 'Recency', 'NumWebPurchases']].mean()
print(profile)

"""**VISUALIZATION**"""

#SCATTER_PLOT(INCOME V/S TOTAL SPENDING)
plt.figure(figsize=(12,8))

sns.scatterplot(data, x='Income', y='MntTotal', hue='Cluster', palette='viridis', alpha=0.7, s=100)
plt.title('Customer Segments: Income Vs. Total Spending')
plt.xlabel('Annual Income')
plt.ylabel('Total Spending')
plt.legend(title='Cluster', loc='upper right')
plt.show()
plt.savefig('/content/Task-2-Customer-Segmentation/customer_segments_plot.png')

#INACTIVITY BOXPLOT
plt.figure(figsize=(10, 6))
# Use 'Days_Since_Last_Purchase' if you renamed it earlier
sns.boxplot(x='Cluster', y='Recency', data=data, palette='Set2')
plt.title('Inactivity Period by Customer Segment')
plt.xlabel('Customer Cluster')
plt.ylabel('Days Since Last Purchase')
plt.show()

centroids_scaled = kmeans.cluster_centers_


centroids_real = scaler.inverse_transform(centroids_scaled)


centroid_df = pd.DataFrame(centroids_real, columns=features)
centroid_df['Cluster'] = [f'Cluster {i}' for i in range(len(centroid_df))]

print("--- Average Profile per Segment ---")
print(centroid_df)

import os

# Save the final segmented data to your task folder
file_path = '/content/Task-2-Customer-Segmentation/segmented_customers.csv'

# Extract the directory path from the file path
directory = os.path.dirname(file_path)

# Create the directory if it doesn't exist
os.makedirs(directory, exist_ok=True)

data.to_csv(file_path, index=False)

print(f"Data saved to {file_path}")

"""# 📈 Final Insights & Business Recommendations

## 1. Segment Profiles
After performing K-Means clustering, we identified 4 distinct customer groups:

*   **Cluster 0: VIPs** - This people have high income and are heavy spenders. They are the regulars.
*   **Cluster 1: Loosing Customers** -They are the once with high recency with no purchase in more than 3 months.
*   **Cluster 2: Shopoholics** -They try to use as many cupons and discounts as possible and are regularly going through sites
*   **Cluster 3: Minimalists** -People with low income and tight budget who stick to buying things that are mandatorily required.

## 2. Key Insights
*   **Income vs. Spending:** There is a direct 0.79 correlation, meaning as income rises, luxury spending (Wine/Meat) increases significantly.
*   **Churn Risk:** Over 15% of our previously high-spending customers have not made a purchase in 90 days.

## 3. Strategic Recommendations
1.  There should be special early availabilty, exclusively for the VIPS in order to keep them indulged.
2.  To customers from segment1, we should try to make them intersted in making a purchase again by sending them cupons & discounts.
3. Make some intersting offers like "BUY 1 GET 1 FREE", "BUY 3 FOR 1500" etc , this will help attract them and keep them hinged.

"""

