# -*- coding: utf-8 -*-
"""EDA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pMRV4IgKYdHOdVBaijp0qZ1P5SHFCy9k

# **ARYA TIWARI**
"""

#IMPORTING LIBRARIES
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#DATA LOADING
data_source="https://github.com/Arya17-git/OIBSIP/raw/refs/heads/main/retail_sales_dataset.csv"
data=pd.read_csv(data_source)
data.head()

"""**STUDYIND DATASET CHARACTERISTICS**"""

data.shape

data.info()

data.isnull().sum()

numeric_columns=data.select_dtypes(include=['number']).columns
categorical_columns=data.select_dtypes(include=['object']).columns
print(f"Total Numeric Columns: {len(numeric_columns)}")
print(f"Numeric Column Names: {list(numeric_columns)}")

print(f"\nTotal Categorical Columns: {len(categorical_columns)}")
print(f"Categorical Column Names: {list(categorical_columns)}")

data['Date']=pd.to_datetime(data['Date'])
data['Date']

"""**DESCRIPTIVE STATISTICS**"""

data.describe()

mode= data[['Age', 'Quantity', 'Total Amount']].mode().iloc[0]
print("Mode Values:\n", mode)

# Summary for categorical (text-based) columns
categorical_stats = data[['Gender', 'Product Category']].describe()
print(categorical_stats)

sales_std = data['Total Amount'].std()
print(f"Standard Deviation of Sales: {sales_std}")

"""**TIME SERIES ANALYSIS**"""

###STATIONARITY###
##Ho (Null Hypothesis): The time series data is non-stationary
##H1 (alternate Hypothesis): The time series data is stationary
from statsmodels.tsa.stattools import adfuller

# We must use a Series with a frequency (Daily Sums)
daily_sales = data.resample('D', on='Date')['Total Amount'].sum()

# Run the test
result = adfuller(daily_sales)

print('ADF Statistic: %f' % result[0])
print('p-value: %f' % result[1])

if result[1] <= 0.05:
    print("Conclusion: Data is Stationary (H1)")
    print("THERE IS NO NEED OF DIFFERENCING")
else:
    print("Conclusion: Data is Non-Stationary (H0)")

##MOVING AVERAGE##
data= data.sort_values('Date')

#7-day SMA
data['SMA_7'] = data['Total Amount'].rolling(window=7).mean()

#30-day SMA
data['SMA_30'] = data['Total Amount'].rolling(window=30).mean()

#Visualization
plt.figure(figsize=(12,6))
plt.plot(data['Date'], data['Total Amount'], label='Actual Daily Sales', alpha=0.3) # Faded
plt.plot(data['Date'], data['SMA_7'], label='7-Day Trend', color='orange', linewidth=2)
plt.plot(data['Date'], data['SMA_30'], label='30-Day Trend', color='red', linewidth=2)

plt.title('Retail Sales: Moving Average Smoothing')
plt.legend()
plt.show()

##EXPONENTIAL MOVING AVERAGE
data['EMA_7'] = data['Total Amount'].ewm(span=7, adjust=False).mean()

#Visualization
plt.figure(figsize=(12,6))
plt.plot(data['Date'], data['Total Amount'], label='Actual Sales', alpha=0.3, color='gray')
plt.plot(data['Date'], data['EMA_7'], label='7-Day EMA', color='green', linewidth=2)

plt.title('Retail Sales: Exponential Moving Average (EMA)')
plt.xlabel('Date')
plt.ylabel('Total Sales')
plt.legend()
plt.show()

##OUTLIER DETECTION & REMOVAL##
plt.figure(figsize=(8, 4))
sns.boxplot(x=data['Total Amount'])
plt.title('Box Plot of Total Sales')
plt.show()

# Calculate IQR
Q1 = data['Total Amount'].quantile(0.25)
Q3 = data['Total Amount'].quantile(0.75)
IQR = Q3 - Q1

# Define bounds
lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

# Identify outliers
outliers = data[(data['Total Amount'] < lower_bound) | (data['Total Amount'] > upper_bound)]
print(f"Number of outliers detected: {len(outliers)}")
if len(outliers)==0:
  print("NO OUTLIERS DETECTED")
else:
  print("OUTLIERS DETECTED")

"""**DEMOGRAPHIC ANALYSIS**"""

bins = [18, 28, 40, 47, 58, 70, 100]
labels = ['18-28', '28-40', '41-47', '48-58', '59-70', '75+']
data['Age Group'] = pd.cut(data['Age'], bins=bins, labels=labels, right=False)

#Visualization
plt.figure(figsize=(6, 4))
sns.countplot(data=data, x='Gender', palette='pastel')
plt.title('Customer Distribution by Gender')
plt.show()

##purchacing  behaviour analysis
# Spending by Age Group and Product Category
age_product_spend = data.groupby(['Age Group', 'Product Category'])['Total Amount'].sum().unstack()
age_product_spend

"""**VISUALIZATIONS**"""

import matplotlib.pyplot as plt
import seaborn as sns

# Resample to Monthly to make the line smoother
monthly_trend = data.resample('ME', on='Date')['Total Amount'].sum()

plt.figure(figsize=(12, 5))
sns.lineplot(x=monthly_trend.index, y=monthly_trend.values, marker='o')
plt.title('Monthly Sales Trend (2023)', fontsize=12)
plt.ylabel('Total Revenue')
plt.grid(True, alpha=0.2)
plt.show()

##Seasonality Analysis##
#To reset the index column as date no longer needs to be the Index Column
data.reset_index(inplace=True)

#To extract the day name
data['Day_of_Week'] = data['Date'].dt.day_name()
day_order = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']

#Avg Sales per day
avg_daily_sales = data.groupby('Day_of_Week')['Total Amount'].mean().reindex(day_order)

#Visualization
plt.figure(figsize=(10, 5))
sns.barplot(x=avg_daily_sales.index, y=avg_daily_sales.values, palette='viridis')
plt.title('Average Sales by Day of the Week', fontsize=14)
plt.xlabel('Day of the Week', fontsize=12)
plt.ylabel('Average Sales ($)', fontsize=12)
plt.show()

##Product Analysis
plt.figure(figsize=(8, 5))
# Calculate sum per category and sort for better visuals
category_sales = data.groupby('Product Category')['Total Amount'].sum().sort_values(ascending=False)

sns.barplot(x=category_sales.index, y=category_sales.values)
plt.title('Total Revenue by Product Category', fontsize=12)
plt.ylabel('Total Sales')
plt.xlabel('Product Category')
plt.show()

# Pivot Table
pivot_table = data.pivot_table(index='Age Group', columns='Product Category', values='Total Amount', aggfunc='sum')

plt.figure(figsize=(10, 6))
sns.heatmap(pivot_table, annot=True, fmt=".0f", cmap='YlGnBu', cbar_kws={'label': 'Total Spend'})
plt.title('Heatmap: Spending Power by Age & Category', fontsize=14)
plt.show()

"""**ANALYSIS REPORT**

 1.DATASET
*   Dataset has total of 9 variables,out of which 5 are numeric and 4 are categorical
*   Dataset has no null values
*   There are no outliers

2.DESCRIPTIVE STATICS
*   Dataset contains 1000 transactions over 1 year
*   Customers are mostly aged 29–53
*   Most purchases involve 2–3 items
*   Prices and total amounts show high variability
*  Data is right-skewed (few high values pulling averages up)
*   The dataset shows a balanced gender distribution, with females slightly outnumbering males. Among product categories, clothing emerges as the most popular, accounting for the highest number of transactions, while other categories share the remaining demand.

**ACTIONABLE RECOOMENDATIONS**

1.**Double down on high-performing categories**
Electronics & Clothing generate the highest revenue

Clothing has the highest frequency, Electronics has high value per sale

***Action:***
Increase inventory in these categories,
Run targeted promotions:
Clothing → volume discounts,
Electronics → premium bundles

2.**Target age groups differently**
From your heatmap:

18–28 → spends most on Clothing

28–40 → balanced across all categories (goldmine group)

48–58 → high spending again (unexpected comeback arc)

59+ → prefers Electronics

***Action:***
Personalized marketing:
Young users → fashion campaigns, Instagram ads;
Middle-aged → combo offers (all categories);
Older users → electronics-focused ads


3.**Weekend sales strategy**
Saturday = highest sales,
Sunday decent, weekdays lower

***Action:***
Run:
Flash sales on weekends,
Limited-time offers on Saturday,
Push ads on Friday evening

4.**Gender-based targeting**

Slightly more female customers

Clothing dominates → aligns with that trend

***Action:***
Focus slightly more campaigns toward female audience,
but don’t ignore males (it’s 49%, not extinct)


**The analysis reveals that Electronics and Clothing categories contribute the most to revenue, with distinct purchasing patterns across age groups. Sales are highest during weekends, particularly Saturdays, indicating an opportunity for targeted promotions. Seasonal trends suggest peak sales in mid-year and during festive periods. High variability in daily sales highlights the need for stabilization strategies such as loyalty programs and subscription models. Additionally, the stationary nature of the time series data allows for effective forecasting without further transformation.**
"""
